"""rename fund_category to purpose

Revision ID: 6ad63b49a15d
Revises: a9b445ef31d3
Create Date: 2026-08-09 18:24:48.959026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ad63b49a15d'
down_revision = 'a9b445ef31d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giving', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=50), nullable=True))
        batch_op.drop_column('fund_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giving', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_category', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
